// Page templates. Every page is plain HTML generated from content/site.json.
import {
  esc, md, plain, attrs, pad, formatDate,
  resolveImage, fillImg, naturalImg, ytThumb, waLink,
} from "./lib.mjs";

const ICON = {
  arrow: `<svg class="i" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>`,
  arrowUpRight: `<svg class="i" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17 17 7M8 7h9v9"/></svg>`,
  play: `<svg class="i i--fill" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5.5v13l11-6.5z"/></svg>`,
  pause: `<svg class="i i--fill" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 5h3.5v14H7zM13.5 5H17v14h-3.5z"/></svg>`,
  close: `<svg class="i" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>`,
  sound: `<svg class="i" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h4l5 4V6L8 10H4z"/><path class="wave" d="M16.5 8.5a5 5 0 0 1 0 7M19 6a8.5 8.5 0 0 1 0 12"/></svg>`,
  mute: `<svg class="i" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h4l5 4V6L8 10H4z"/><path d="M17 9.5l5 5M22 9.5l-5 5"/></svg>`,
  whatsapp: `<svg class="i i--fill" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.2A9.7 9.7 0 0 0 3.7 16.9L2.3 21.8l5-1.3A9.7 9.7 0 1 0 12 2.2zm0 17.7a8 8 0 0 1-4.1-1.1l-.3-.2-3 .8.8-2.9-.2-.3A8 8 0 1 1 12 19.9zm4.4-6c-.2-.1-1.4-.7-1.7-.8-.2-.1-.4-.1-.5.1l-.8 1c-.1.2-.3.2-.5.1a6.6 6.6 0 0 1-3.3-2.9c-.2-.4.2-.4.7-1.3.1-.2 0-.3 0-.4l-.8-1.8c-.2-.5-.4-.4-.5-.4h-.5a.9.9 0 0 0-.7.3 2.8 2.8 0 0 0-.9 2.1 5 5 0 0 0 1 2.6 11.2 11.2 0 0 0 4.3 3.8c1.6.7 2.2.7 3 .6a2.6 2.6 0 0 0 1.7-1.2 2.1 2.1 0 0 0 .2-1.2c-.1-.1-.3-.2-.5-.3z"/></svg>`,
};

// Full-bleed cover images on screens taller than 3:2 need a wider file than 100vw.
const HERO_SIZES = "(max-aspect-ratio: 3/2) 150vh, 100vw";

const wordmark = (tag = "span", cls = "wordmark") =>
  `<${tag} class="${cls}">The Reel <em>Romance</em></${tag}>`;

// ================================================================ layout
export function layout(c, page) {
  const { site, contact } = c;
  const b = page.base; // relative path to site root ("" or "../../")
  const canonical = site.url.replace(/\/$/, "") + page.path;
  const share = resolveImage(page.shareImage || { src: site.shareImage }, page.ctx);
  const shareUrl = share
    ? share.jpg.startsWith("http") ? share.jpg : site.url.replace(/\/$/, "") + "/" + share.jpg.replace(/^(\.\.\/)+/, "")
    : "";
  const title = page.title || site.title;
  const desc = page.description || site.description;

  const jsonld = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    name: site.name,
    url: site.url,
    description: site.description,
    image: shareUrl,
    telephone: contact.phoneDisplay,
    email: contact.email || undefined,
    priceRange: "₹₹₹",
    address: { "@type": "PostalAddress", addressLocality: site.city, addressRegion: site.region, addressCountry: site.country },
    areaServed: site.areaServed,
    sameAs: [contact.instagram, contact.youtube].filter(Boolean),
  };

  return `<!doctype html>
<!-- Generated by build.mjs from content/site.json — edit that file, not this one. -->
<html lang="en-IN" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${esc(canonical)}">
<meta name="theme-color" content="#141210">
<meta name="color-scheme" content="light">
<meta property="og:type" content="website">
<meta property="og:site_name" content="${esc(site.name)}">
<meta property="og:locale" content="${esc(site.locale)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:url" content="${esc(canonical)}">
${shareUrl ? `<meta property="og:image" content="${esc(shareUrl)}">\n<meta property="og:image:alt" content="${esc(site.name)}">` : ""}
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="${b}assets/icons/favicon.svg" type="image/svg+xml">
<link rel="icon" href="${b}assets/icons/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="${b}assets/icons/apple-touch-icon.png">
<link rel="manifest" href="${b}site.webmanifest">
<link rel="preload" href="${b}assets/fonts/cormorant-garamond.woff" as="font" type="font/woff" crossorigin>
<link rel="preload" href="${b}assets/fonts/hanken-grotesk.woff" as="font" type="font/woff" crossorigin>
${page.preload || ""}
<link rel="stylesheet" href="${b}assets/css/site.css?v=${page.v.css}">
<script>document.documentElement.classList.replace('no-js','js')</script>
<script type="application/ld+json">${JSON.stringify(jsonld)}</script>
</head>
<body class="${page.bodyClass || ""}">
<a class="skip" href="#main">Skip to content</a>
${header(c, page)}
<main id="main">
${page.body}
</main>
${footer(c, page)}
${playerDialog()}
${page.bodyClass === "page-404" ? "" : `<a class="btn float-cta" href="${page.isHome ? "" : b}#enquire" data-float-cta>Enquire ${ICON.arrow}</a>`}
<script src="${b}assets/js/site.js?v=${page.v.js}" defer></script>
</body>
</html>
`;
}

function nav(c, b, onHome) {
  const h = onHome ? "" : `${b}`;
  const links = [
    ["Work", `${h}#work`],
    ["Films", `${h}#films`],
    ["Stories", `${h}#stories`],
    ["BTS", `${h}#bts`],
    ["How it works", `${h}#process`],
  ];
  return links;
}

function header(c, page) {
  const b = page.base;
  const links = nav(c, b, page.isHome);
  const home = page.isHome ? "#top" : `${b}`;
  return `<header class="site-header" data-header>
  <div class="site-header__inner">
    <a class="site-header__logo" href="${home}" aria-label="${esc(c.site.name)} — home">${wordmark()}</a>
    <nav class="site-nav" aria-label="Main">
      ${links.map(([t, h]) => `<a href="${h}">${t}</a>`).join("")}
    </nav>
    <a class="btn btn--sm site-header__cta" href="${page.isHome ? "" : b}#enquire">Enquire</a>
    <button class="menu-toggle" type="button" aria-controls="menu" aria-expanded="false" data-menu-open>
      <span class="menu-toggle__label">Menu</span><span class="menu-toggle__icon" aria-hidden="true"><i></i><i></i></span>
    </button>
  </div>
</header>
<dialog class="menu" id="menu" aria-label="Menu">
  <div class="menu__top">
    ${wordmark()}
    <button class="menu__close" type="button" data-menu-close aria-label="Close menu">${ICON.close}</button>
  </div>
  <nav class="menu__nav" aria-label="Menu">
    ${links.map(([t, h], i) => `<a href="${h}" style="--i:${i}"><span class="menu__num">${pad(i + 1)}</span>${t}</a>`).join("")}
    <a href="${page.isHome ? "" : b}#enquire" style="--i:${links.length}"><span class="menu__num">${pad(links.length + 1)}</span><em>Enquire</em></a>
  </nav>
  <div class="menu__foot">
    <a href="${waLink(c.contact.whatsapp)}" target="_blank" rel="noopener">${ICON.whatsapp} WhatsApp</a>
    ${c.contact.email ? `<a href="mailto:${esc(c.contact.email)}">${esc(c.contact.email)}</a>` : ""}
  </div>
</dialog>`;
}

function footer(c, page) {
  const { contact, site } = c;
  const b = page.base;
  const h = page.isHome ? "" : b;
  const year = new Date().getFullYear();
  return `<footer class="site-footer">
  <div class="wrap">
    <div class="site-footer__grid">
      <div>
        <p class="label">Say hello</p>
        <ul class="site-footer__list">
          <li><a href="${waLink(contact.whatsapp)}" target="_blank" rel="noopener">WhatsApp ${esc(contact.phoneDisplay)}</a></li>
          ${contact.email ? `<li><a href="mailto:${esc(contact.email)}">${esc(contact.email)}</a></li>` : ""}
          ${contact.instagram ? `<li><a href="${esc(contact.instagram)}" target="_blank" rel="noopener">Instagram</a></li>` : ""}
          ${contact.youtube ? `<li><a href="${esc(contact.youtube)}" target="_blank" rel="noopener">YouTube</a></li>` : ""}
        </ul>
      </div>
      <div>
        <p class="label">Explore</p>
        <ul class="site-footer__list">
          ${nav(c, b, page.isHome).map(([t, u]) => `<li><a href="${u}">${t}</a></li>`).join("")}
          <li><a href="${h}#enquire">Enquire</a></li>
        </ul>
      </div>
      <div>
        <p class="label">Based in</p>
        <p class="site-footer__text">${esc(site.city)}, India.<br>Travelling across India &amp; beyond.</p>
      </div>
    </div>
    <p class="site-footer__mark" aria-hidden="true">${wordmark("span", "wordmark wordmark--huge")}</p>
    <div class="site-footer__base">
      <span>© ${year} ${esc(site.name)}</span>
      <span>Photography · Films · BTS</span>
      <a href="#main" data-to-top>Back to top ↑</a>
    </div>
  </div>
</footer>`;
}

function playerDialog() {
  return `<dialog class="player" id="player" aria-label="Film player">
  <button class="player__close" type="button" data-player-close aria-label="Close film">${ICON.close}</button>
  <div class="player__stage"><div class="player__frame" data-player-frame></div></div>
</dialog>`;
}

// ================================================================ pieces
const head = (s, id, { dark = false, align = "" } = {}) => `
  <div class="section-head ${align}">
    <p class="label${dark ? " label--light" : ""}">${esc(s.kicker)}</p>
    <h2 class="h2" ${id ? `id="${id}"` : ""} data-reveal>${md(s.heading)}</h2>
  </div>`;

function filmCard(film, ctx, { big = true } = {}) {
  const poster = film.poster && film.poster.src
    ? fillImg(film.poster, ctx, { sizes: "(max-width: 599px) 190vw, (min-width: 1600px) 1500px, 92vw" })
    : `<img class="fill" src="${ytThumb(film.youtube)}" alt="${esc(film.title)}" loading="lazy" decoding="async">`;
  return `<figure class="film ${big ? "film--big" : ""}" data-reveal>
    <button class="film__poster frame" type="button" data-film="${esc(film.youtube)}" aria-label="Play film: ${esc(film.title)}${film.couple ? " — " + esc(film.couple) : ""}">
      ${poster}
      <span class="film__bars" aria-hidden="true"></span>
      <span class="film__play" aria-hidden="true">${ICON.play}<span>Play film</span></span>
    </button>
    <figcaption class="film__caption">
      <span class="film__title">${esc(film.title)}</span>
      <span class="film__meta">${[film.couple, film.place].filter(Boolean).map(esc).join(" · ")}</span>
    </figcaption>
  </figure>`;
}

function btsPhones(items, { label = true } = {}) {
  return `<div class="bts__phones">
    ${items.map((v, i) => `<figure class="phone" data-reveal style="--d:${i * 90}ms">
      <div class="phone__screen">
        <video class="phone__video" muted playsinline loop preload="none" data-src="${esc(v.src)}" aria-label="${esc(v.label || "Behind-the-scenes reel")}"></video>
        <span class="phone__label">${esc(v.label || "")}</span>
        <button class="phone__sound" type="button" data-sound aria-pressed="false" aria-label="Turn sound on">${ICON.mute}${ICON.sound}</button>
        <button class="phone__play" type="button" data-play aria-label="Play reel">${ICON.play}</button>
      </div>
      ${label ? `<figcaption class="phone__caption"><span>BTS ${pad(i + 1)}</span></figcaption>` : ""}
    </figure>`).join("")}
  </div>`;
}

function ctaBand(c, b) {
  return `<section class="cta-band">
  <div class="wrap cta-band__inner">
    <p class="cta-band__text" data-reveal>Planning your own? <em>Tell us about your day.</em></p>
    <a class="btn btn--light" href="${b}#enquire">Start the conversation ${ICON.arrow}</a>
  </div>
</section>`;
}

// ================================================================ home
export function home(c, ctx) {
  const { hero, prologue, frames, films, stories, bts, services, process, testimonials, faq, enquiry, contact } = c;
  const published = stories.items.filter((s) => s.published);
  const slides = hero.slides;

  const heroHtml = `<section class="hero" id="top" data-hero aria-label="Introduction">
  <div class="hero__media" aria-live="off">
    ${slides.map((s, i) => `<figure class="hero__slide${i === 0 ? " is-active" : ""}" data-slide data-scene="${esc(s.scene || "")}">
      ${fillImg(s, ctx, { sizes: HERO_SIZES, eager: i === 0 })}
    </figure>`).join("")}
  </div>
  <div class="hero__shade" aria-hidden="true"></div>
  <div class="letterbox" aria-hidden="true"><i></i><i></i></div>
  <div class="hero__content wrap">
    <p class="hero__eyebrow"><span>${esc(hero.eyebrow)}</span><span>${esc(hero.place)}</span></p>
    <h1 class="hero__title">${hero.titleLines.map((l, i) => `<span class="hero__line" style="--i:${i}"><span>${md(l)}</span></span>`).join(" ")}</h1>
    <div class="hero__foot">
      <p class="hero__intro">${esc(hero.intro)}</p>
      <div class="hero__ctas">
        <a class="btn btn--light" href="#work">See the work ${ICON.arrow}</a>
        <a class="btn btn--ghost-light" href="#enquire">Enquire</a>
      </div>
    </div>
  </div>
  <div class="hud" aria-hidden="true">
    <span class="hud__rec"><i></i>REC</span>
    <span class="hud__tc" data-timecode>00:00:00:00</span>
  </div>
  <div class="hero__controls">
    <p class="hero__scene"><span data-scene-index>01</span> / ${pad(slides.length)} <span class="hero__scene-name" data-scene-name>${esc(slides[0].scene || "")}</span></p>
    <div class="hero__dots">
      ${slides.map((_, i) => `<button type="button" class="hero__dot${i === 0 ? " is-active" : ""}" data-goto="${i}" aria-label="Show photo ${i + 1} of ${slides.length}"><i></i></button>`).join("")}
      <button type="button" class="hero__pause" data-hero-pause aria-label="Pause slideshow">${ICON.pause}${ICON.play}</button>
    </div>
  </div>
</section>`;

  const [pA, pB] = prologue.images;
  const ideaPhoto = (img, cls, frame, sizes, d) => img ? `<figure class="idea__photo ${cls}" data-reveal style="--d:${d}ms">
        <div class="frame ${frame}">${fillImg(img, ctx, { sizes })}</div>
        ${img.caption ? `<figcaption>${esc(img.caption)}</figcaption>` : ""}
      </figure>` : "";
  const prologueHtml = `<section class="idea" aria-labelledby="idea-h">
  <div class="wrap">
    <header class="idea__head">
      <p class="label idea__kicker">${esc(prologue.kicker)}</p>
      <h2 class="h2 idea__title" id="idea-h" data-reveal>${md(prologue.heading)}</h2>
    </header>
    <div class="idea__spread">
      ${ideaPhoto(pA, "idea__photo--a", "frame--portrait", "(min-width: 1024px) 34vw, (min-width: 600px) 46vw, 50vw", 0)}
      <div class="idea__text" data-reveal style="--d:120ms">
        <p class="lead">${esc(prologue.body)}</p>
        <p class="idea__quote">${esc(prologue.aside)}</p>
      </div>
      ${ideaPhoto(pB, "idea__photo--b", "frame--tall", "(min-width: 1024px) 24vw, (min-width: 600px) 46vw, 50vw", 220)}
    </div>
  </div>
</section>`;

  const reelHtml = `<section class="reel" id="work" aria-labelledby="work-h" data-reel>
  <div class="reel__sticky">
    <div class="wrap reel__head">
      <div>
        <p class="label">${esc(frames.kicker)}</p>
        <h2 class="h2" id="work-h" data-reveal>${md(frames.heading)}</h2>
      </div>
      <p class="reel__note"><span class="reel__count"><span data-reel-index>01</span> / ${pad(frames.items.length)}</span><span class="reel__hint">${esc(frames.note)}</span></p>
    </div>
    <div class="reel__viewport" data-reel-viewport tabindex="0" aria-label="Selected frames, scroll horizontally">
      <ol class="reel__track" data-reel-track>
        ${frames.items.map((f, i) => `<li class="reel__frame">
          <figure>
            ${naturalImg(f, ctx, { sizes: "(min-width: 1024px) 60vw, 86vw" })}
            <figcaption><span class="reel__num">${pad(i + 1)}</span>${esc(f.caption || "")}</figcaption>
          </figure>
        </li>`).join("")}
      </ol>
    </div>
    <div class="wrap reel__progress" aria-hidden="true"><i data-reel-progress></i></div>
  </div>
</section>`;

  const filmsHtml = films.items.length ? `<section class="films dark" id="films" aria-labelledby="films-h">
  <div class="wrap">
    <div class="films__head">
      ${head(films, "films-h", { dark: true })}
      <p class="body body--light" data-reveal>${esc(films.body)}</p>
    </div>
    <div class="films__list">
      ${films.items.map((f, i) => filmCard(f, ctx, { big: i === 0 })).join("")}
    </div>
  </div>
</section>` : "";

  // Published stories get their own page; "teaser" stories show a card only,
  // until their photos and details are added.
  const listed = stories.items.filter((s) => s.published || s.teaser);
  const featureFirst = listed.length !== 2; // two stories sit side by side as equals
  const storyCard = (s, i) => {
    const feature = featureFirst && i === 0;
    const inner = `
          <div class="frame story-card__media">${fillImg(s.cover, ctx, { sizes: feature ? "(min-width: 1024px) 60vw, 120vw" : "(min-width: 600px) 50vw, 120vw" })}</div>
          <div class="story-card__body">
            <p class="label">${[formatDate(s.date), s.place].filter(Boolean).map(esc).join(" · ") || "Real wedding"}</p>
            <h3 class="story-card__title">${esc(s.couple).replace("&amp;", "<em>&amp;</em>")}</h3>
            ${s.summary ? `<p class="body">${esc(s.summary)}</p>` : ""}
            ${s.published
              ? `<span class="link-arrow">View their story ${ICON.arrow}</span>`
              : `<span class="story-card__soon">Full story coming soon</span>`}
          </div>`;
    return `<article class="story-card${feature ? " story-card--feature" : ""}${s.published ? "" : " story-card--teaser"}" data-reveal style="--d:${i * 120}ms">
        ${s.published ? `<a class="story-card__link" href="stories/${esc(s.slug)}/">${inner}</a>` : `<div class="story-card__link">${inner}</div>`}
      </article>`;
  };
  const storiesHtml = listed.length ? `<section class="stories" id="stories" aria-labelledby="stories-h">
  <div class="wrap">
    ${head(stories, "stories-h")}
    <div class="stories__list stories__list--${Math.min(listed.length, 3)}">
      ${listed.map(storyCard).join("")}
    </div>
  </div>
</section>` : "";

  const btsHtml = bts.items.length ? `<section class="bts" id="bts" aria-labelledby="bts-h">
  <div class="wrap bts__grid">
    <div class="bts__text">
      ${head(bts, "bts-h")}
      <p class="body" data-reveal>${esc(bts.body)}</p>
      <p class="bts__hint label">Tap a reel for sound</p>
    </div>
    ${btsPhones(bts.items)}
  </div>
</section>` : "";

  const servicesHtml = `<section class="services" id="services" aria-labelledby="services-h">
  <div class="wrap">
    ${head(services, "services-h")}
    <ul class="services__list" data-services>
      ${services.items.map((s, i) => {
        const r = s.image && s.image.src ? resolveImage(s.image, ctx) : null;
        return `<li class="service" data-reveal ${r ? `data-preview="${esc(r.src)}"` : ""}>
          <span class="service__num">${pad(i + 1)}</span>
          <h3 class="service__name">${esc(s.name)}</h3>
          <p class="service__line">${esc(s.line)}</p>
          ${s.from ? `<p class="service__from"><span class="label">From</span> ${esc(s.from)}</p>` : ""}
        </li>`;
      }).join("")}
    </ul>
  </div>
  <div class="services__preview" aria-hidden="true" data-services-preview><img alt="" decoding="async"></div>
</section>`;

  const processHtml = `<section class="process dark" id="process" aria-labelledby="process-h">
  <div class="wrap">
    ${head(process, "process-h", { dark: true })}
    <ol class="process__steps">
      ${process.steps.map((s, i) => `<li class="step" data-reveal style="--d:${i * 90}ms">
        <span class="step__num">${pad(i + 1)}</span>
        <h3 class="step__title">${esc(s.title)}</h3>
        <p class="step__body">${esc(s.body)}</p>
      </li>`).join("")}
    </ol>
  </div>
</section>`;

  const testimonialsHtml = testimonials.items.length ? `<section class="words" aria-label="${esc(testimonials.kicker)}">
  <div class="wrap">
    <p class="label">${esc(testimonials.kicker)}</p>
    <div class="words__list">
      ${testimonials.items.map((t) => `<figure class="word" data-reveal>
        <blockquote><p>“${esc(t.quote)}”</p></blockquote>
        <figcaption><span>${esc(t.name)}</span>${t.detail ? ` <span class="word__detail">${esc(t.detail)}</span>` : ""}</figcaption>
      </figure>`).join("")}
    </div>
  </div>
</section>` : "";

  const faqHtml = faq.items.length ? `<section class="faq" aria-labelledby="faq-h">
  <div class="wrap faq__grid">
    <div><p class="label">${esc(faq.kicker)}</p><h2 class="h2" id="faq-h">Good to <em>know.</em></h2></div>
    <div class="faq__list">
      ${faq.items.map((f) => `<details class="faq__item"><summary>${esc(f.q)}</summary><div class="faq__a"><p>${esc(f.a)}</p></div></details>`).join("")}
    </div>
  </div>
</section>` : "";

  const enquiryHtml = enquiryBlock(c);

  const body = [heroHtml, prologueHtml, reelHtml, filmsHtml, storiesHtml, btsHtml, servicesHtml, processHtml, testimonialsHtml, faqHtml, enquiryHtml].join("\n");

  const first = resolveImage(slides[0], ctx);
  const preload = first && first.srcset
    ? `<link rel="preload" as="image" imagesrcset="${esc(first.srcset)}" imagesizes="${HERO_SIZES}" fetchpriority="high">`
    : "";
  return { body, preload };
}

function enquiryBlock(c) {
  const { enquiry, contact } = c;
  return `<section class="enquire dark" id="enquire" aria-labelledby="enquire-h">
  <div class="wrap enquire__grid">
    <div class="enquire__intro">
      <p class="label label--light">${esc(enquiry.kicker)}</p>
      <h2 class="h2 h2--xl" id="enquire-h" data-reveal>${md(enquiry.heading)}</h2>
      <p class="body body--light" data-reveal>${esc(enquiry.body)}</p>
      <ul class="enquire__direct">
        <li><a class="btn btn--light" href="${waLink(contact.whatsapp)}" target="_blank" rel="noopener">${ICON.whatsapp} WhatsApp us</a></li>
        ${contact.email ? `<li><a class="btn btn--ghost-light" href="mailto:${esc(contact.email)}">${esc(contact.email)}</a></li>` : ""}
      </ul>
    </div>
    <form class="form" data-enquiry novalidate
      data-whatsapp="${esc(contact.whatsapp)}"
      ${contact.formEndpoint ? `data-endpoint="${esc(contact.formEndpoint)}"` : ""}
      aria-describedby="form-note">
      <div class="form__row">
        <div class="field">
          <label for="f-name">Your names <span class="req" aria-hidden="true">*</span></label>
          <input id="f-name" name="name" autocomplete="name" required placeholder="e.g. Priya & Arjun">
          <p class="field__error" id="f-name-err" hidden>Please tell us your names.</p>
        </div>
      </div>
      <div class="form__row form__row--2">
        <div class="field">
          <label for="f-phone">Phone / WhatsApp</label>
          <input id="f-phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="+91">
        </div>
        <div class="field">
          <label for="f-email">Email</label>
          <input id="f-email" name="email" type="email" autocomplete="email" placeholder="you@example.com">
          <p class="field__error" id="f-email-err" hidden>That email doesn't look right.</p>
        </div>
      </div>
      <div class="form__row form__row--2">
        <div class="field">
          <label for="f-date">Wedding date</label>
          <input id="f-date" name="date" placeholder="e.g. 14 Feb 2027, or just the month">
        </div>
        <div class="field">
          <label for="f-place">City / venue</label>
          <input id="f-place" name="place" autocomplete="address-level2" placeholder="Bangalore, Udaipur, Goa…">
        </div>
      </div>
      <fieldset class="field field--chips">
        <legend>What are you looking for?</legend>
        <div class="chips">
          ${enquiry.services.map((s, i) => `<label class="chip"><input type="checkbox" name="services" value="${esc(s)}"><span>${esc(s)}</span></label>`).join("")}
        </div>
      </fieldset>
      <div class="field">
        <label for="f-msg">Tell us a little more</label>
        <textarea id="f-msg" name="message" rows="4" placeholder="The vibe, the venue, the plans, the chaos…"></textarea>
      </div>
      <div class="form__actions">
        <button class="btn btn--light btn--lg" type="submit" data-submit>
          <span data-submit-label>${contact.formEndpoint ? "Send enquiry" : "Send on WhatsApp"}</span> ${ICON.arrow}
        </button>
        <p class="form__note" id="form-note">${contact.formEndpoint
          ? "We reply within a day. Your details are only used to answer your enquiry."
          : "Opens WhatsApp with your enquiry written out — just press send."}</p>
      </div>
      <p class="form__status" role="status" aria-live="polite" data-status></p>
    </form>
  </div>
</section>`;
}

// ================================================================ story
export function story(c, s, ctx, all) {
  const idx = all.indexOf(s);
  const next = all.length > 1 ? all[(idx + 1) % all.length] : null;
  const b = ctx.base;
  const place = (s.place || "").trim();
  const gallery = s.gallery || [];
  const film = s.film ? { youtube: s.film, title: "Wedding Highlight", couple: s.couple, place: place.split(",")[0], poster: gallery[0] || s.cover } : null;
  const meta = [["Date", formatDate(s.date)], ["Place", place], ["We made", (s.services || []).join(", ")]].filter(([, v]) => v);
  const intro = s.intro || s.summary;
  const cols = Math.min(3, Math.max(1, gallery.length));
  const btsItems = (s.bts || []).map((id) => c.bts.items.find((v) => v.id === id)).filter(Boolean);

  const body = `<article class="story">
  <header class="story-hero" data-hero-simple>
    <div class="story-hero__media">${fillImg(s.cover, ctx, { sizes: HERO_SIZES, eager: true })}</div>
    <div class="hero__shade" aria-hidden="true"></div>
    <div class="wrap story-hero__content">
      <p class="label label--light"><a href="${b}#stories">Real weddings</a>${s.date ? ` · ${esc(formatDate(s.date))}` : ""}</p>
      <h1 class="story-hero__title">${esc(s.couple).replace("&amp;", "<em>&amp;</em>")}</h1>
      ${place ? `<p class="story-hero__place">${esc(place)}</p>` : ""}
    </div>
  </header>

  ${intro || meta.length ? `<section class="story-intro">
    <div class="wrap story-intro__grid">
      ${meta.length ? `<dl class="story-meta">
        ${meta.map(([k, v]) => `<div><dt class="label">${k}</dt><dd>${esc(v)}</dd></div>`).join("")}
      </dl>` : "<div></div>"}
      ${intro ? `<p class="lead story-intro__text" data-reveal>${esc(intro)}</p>` : ""}
    </div>
  </section>` : ""}

  ${film ? `<section class="story-film dark"><div class="wrap">${filmCard(film, ctx)}</div></section>` : ""}

  ${gallery.length ? `<section class="gallery" aria-label="Photographs">
    <div class="wrap">
      <div class="gallery__cols gallery__cols--${cols}">
        ${gallery.map((g) => `<figure class="gallery__item" data-reveal>${naturalImg(g, ctx, { sizes: "(min-width: 1024px) 33vw, (min-width: 600px) 50vw, 100vw" })}</figure>`).join("")}
      </div>
    </div>
  </section>` : `<section class="gallery-soon" aria-labelledby="soon-h">
    <div class="wrap gallery-soon__inner">
      <p class="label">The gallery</p>
      <h2 class="h2" id="soon-h" data-reveal>Being edited, <em>frame by frame.</em></h2>
      <p class="body" data-reveal>${esc(s.couple)}’s photographs${s.film ? "" : " and film"} are on their way to this page.</p>
    </div>
  </section>`}

  ${btsItems.length ? `<section class="bts bts--story" aria-labelledby="story-bts-h">
    <div class="wrap bts__grid">
      <div class="bts__text">
        <p class="label">Behind the frame</p>
        <h2 class="h2" id="story-bts-h">The day, <em>as it happened.</em></h2>
        <p class="bts__hint label">Tap a reel for sound</p>
      </div>
      ${btsPhones(btsItems)}
    </div>
  </section>` : ""}

  ${next ? `<nav class="next-story" aria-label="Next story">
    <a class="wrap next-story__link" href="${b}stories/${esc(next.slug)}/">
      <span class="label">Next story</span>
      <span class="next-story__title">${esc(next.couple).replace("&amp;", "<em>&amp;</em>")} ${ICON.arrow}</span>
    </a>
  </nav>` : ""}
</article>
${ctaBand(c, b)}`;

  const cover = resolveImage(s.cover, ctx);
  const preload = cover && cover.srcset
    ? `<link rel="preload" as="image" imagesrcset="${esc(cover.srcset)}" imagesizes="${HERO_SIZES}" fetchpriority="high">`
    : "";
  return { body, preload };
}

// ================================================================ 404
export function notFound(c) {
  return `<section class="lost dark">
  <div class="wrap lost__inner">
    <p class="label label--light">Error 404 · Scene missing</p>
    <h1 class="h2 h2--xl">This frame ended up on the <em>cutting-room floor.</em></h1>
    <p class="body body--light">The page you were looking for isn't here. The rest of the reel is.</p>
    <p><a class="btn btn--light" href="/">Back to the start ${ICON.arrow}</a></p>
  </div>
</section>`;
}
